.PHONY: test bench

test-wal:
	gotestsum --format testname -- -v ./wal/...

bench-wal:
	go test -bench=. -benchmem ./wal/...

test-store:
	gotestsum --format testname -- ./store/...

bench-store:
	go test -bench=. -benchmem ./store/...